### ISSUE TITLE
Future request: add Commerce Products as fieldtype.

### ISSUE THREAD

**Issue by skogendev** [spicywebau/craft-odds-and-ends#15]
The fieldtypes Entries (Search) and Categories (Search) work great. It would be awesome to have the same functionality for Commerce Products as well.

**Comment by Nav33d** [comment]
@skogendev Yes that would be a useful addition. At the moment we are busy with client work but if you send me a PR I would definitely merge it.

Many thanks

**Comment by ttempleton** [comment]
Added now in version 4.1.0.
