### ISSUE TITLE
CRAFT 4

### ISSUE THREAD

**Issue by wmdhosting** [spicywebau/craft-odds-and-ends#22]
Anyone porting this to 4

**Comment by wmdhosting** [comment]
can i pay . so update this to CRAFT 4  
thats only plugin that block me to upgrade..

**Comment by wmdhosting** [comment]
can you at least respond.. 
Update status.. or anything..

**Comment by adrienne** [comment]
@supercooljames i would also love if this got a Craft 4 upgrade. Any plans?

**Comment by ttempleton** [comment]
Hi @supercool! I'm from @spicywebau and we're interested in publishing our own version of the Categories (multiple groups) field type, but first we wanted to check in and confirm whether you have any plans in the future to upgrade this plugin for Craft 4. If this plugin isn't coming to Craft 4, then we'll move ahead with creating a new plugin - though if this plugin would otherwise be abandoned, with your agreement, we'd be happy to maintain it going forward and make sure it all stays available for Craft 4 and beyond.

**Comment by engram-design** [comment]
@ttempleton After chatting with James about the other Supercool plugins, I'd say you have their blessing. We (Verbb) migrated across some of their other plugins, but looking at this plugin, we didn't really feel like it was a good move to have a "misc" plugin that does all sorts of things. Anything that people still require probably should be their own plugin (as you're doing)

I can't speak for them, but I'd honestly say run with it, and bonus if @supercooljames responds if you want the repo transferred to Spicy Web.

**Comment by ttempleton** [comment]
Cheers @engram-design - will give it a week or so, just in case, then we'll proceed with the Categories (multiple groups) field type as a separate plugin (also happy to look at Craft 4 plugins for other functionality from this plugin if there's interest).

**Comment by ttempleton** [comment]
Thanks @supercooljames - we'd like to take it and upgrade it for Craft 4. Greatly appreciated 🙂

**Comment by wmdhosting** [comment]
whats  status. here now..thx

**Comment by ttempleton** [comment]
Ready to start work as soon as the transfer is complete - @supercooljames please let me know if there's anything we need to do on our end regarding the transfer.

**Comment by wmdhosting** [comment]
OK :) thx for info

**Comment by wmdhosting** [comment]
I see you worked on upgrade, is this now ready for  4.. 

I ask becuse there was some other plugin ready for 4..from other developer  
but not showing in plugin store..

**Comment by ttempleton** [comment]
Just released version 4.0.0, for Craft 4.2.1 or later, and that should be showing on the Craft 4 plugin store.

Please note that the plugin name has changed from Tools to Odds & Ends, and the Composer package name has changed from `supercool/tools` to `spicyweb/craft-odds-and-ends`. So if you're updating the plugin using Composer, be sure to follow the instructions in the [3.0.0 release notes](https://github.com/spicywebau/craft-odds-and-ends/blob/14ac2b0a3e9dddb7dc07f887cc9de5dd4cbaeb42/CHANGELOG.md#300---2022-10-18).

**Comment by wmdhosting** [comment]
OK thank you all OK :)
